server:
  port: 8081

spring:
  datasource:
    username: postgres
    password: jon0311
    url: jdbc:postgresql://localhost:5432/taskmanagerdb
  jpa:
    hibernate:
      ddl-auto: create
jwt:
  secret:
    key: ${JWT_KEY:421mkmmklmkm4klrm23kl3m2342341k2l435lkm43kl5mn234234mklmklm2354235325423l4kjjnjhnhjnbhbkbjkbfsdjfsdfgjdthb2342342134sdkfmsdfsddsf}
  token:
    access:
      expiration: ${JWT_ACCESS_EXPIRATION:31536000000}
    refresh:
      expiration: ${JWT_REFRESH_EXPIRATION:31536000000}
